[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["@sparticuz/chromium"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
